var annotated_dup =
[
    [ "Reflection", null, [
      [ "BasicTypes", "class_reflection_1_1_basic_types.html", "class_reflection_1_1_basic_types" ],
      [ "DefaultTypeTraits", "class_reflection_1_1_default_type_traits.html", null ],
      [ "DefaultTypeTraits< Type * >", "class_reflection_1_1_default_type_traits_3_01_type_01_5_01_4.html", "class_reflection_1_1_default_type_traits_3_01_type_01_5_01_4" ],
      [ "DefaultTypeTraits< Type[Size]>", "class_reflection_1_1_default_type_traits_3_01_type[_size]_4.html", "class_reflection_1_1_default_type_traits_3_01_type[_size]_4" ],
      [ "FunctionWrapper", "class_reflection_1_1_function_wrapper.html", null ],
      [ "FunctionWrapper< RetType(*)(Args...)>", "class_reflection_1_1_function_wrapper_3_01_ret_type_07_5_08_07_args_8_8_8_08_4.html", "class_reflection_1_1_function_wrapper_3_01_ret_type_07_5_08_07_args_8_8_8_08_4" ],
      [ "FunctionWrapper< RetType(OwnerType::*)(Args...)>", "class_reflection_1_1_function_wrapper_3_01_ret_type_07_owner_type_1_1_5_08_07_args_8_8_8_08_4.html", "class_reflection_1_1_function_wrapper_3_01_ret_type_07_owner_type_1_1_5_08_07_args_8_8_8_08_4" ],
      [ "FunctionWrapper< RetType(OwnerType::*)>", "class_reflection_1_1_function_wrapper_3_01_ret_type_07_owner_type_1_1_5_08_4.html", "class_reflection_1_1_function_wrapper_3_01_ret_type_07_owner_type_1_1_5_08_4" ],
      [ "FunctionWrapperBase", "class_reflection_1_1_function_wrapper_base.html", "class_reflection_1_1_function_wrapper_base" ],
      [ "LexicalConverter", "struct_reflection_1_1_lexical_converter.html", null ],
      [ "ReverseLexicalConverter", "struct_reflection_1_1_reverse_lexical_converter.html", null ],
      [ "StaticConverter", "struct_reflection_1_1_static_converter.html", null ],
      [ "Type", "class_reflection_1_1_type.html", null ],
      [ "TypeBase", "class_reflection_1_1_type_base.html", "class_reflection_1_1_type_base" ],
      [ "TypeImpl", "class_reflection_1_1_type_impl.html", "class_reflection_1_1_type_impl" ],
      [ "ValueObject", "class_reflection_1_1_value_object.html", "class_reflection_1_1_value_object" ]
    ] ],
    [ "Shape", null, [
      [ "Rectangle", "struct_shape_1_1_rectangle.html", "struct_shape_1_1_rectangle" ]
    ] ],
    [ "std", null, [
      [ "function", "classstd_1_1function.html", null ]
    ] ],
    [ "Utility", null, [
      [ "FPSManager", "class_utility_1_1_f_p_s_manager.html", "class_utility_1_1_f_p_s_manager" ],
      [ "WorkQueueBase", "class_utility_1_1_work_queue_base.html", "class_utility_1_1_work_queue_base" ]
    ] ],
    [ "BasicCsvParser", "class_basic_csv_parser.html", "class_basic_csv_parser" ],
    [ "Caller", "struct_caller.html", [
      [ "Instance", "struct_caller_1_1_instance.html", null ]
    ] ],
    [ "CFileRead", "class_c_file_read.html", "class_c_file_read" ],
    [ "CheckMember", "class_check_member.html", null ],
    [ "CheckMember< Type, void >", "class_check_member_3_01_type_00_01void_01_4.html", null ],
    [ "ClassFunction", "struct_class_function.html", null ],
    [ "ClassFunction< RetType(Type::*)(Args...)>", "struct_class_function_3_01_ret_type_07_type_1_1_5_08_07_args_8_8_8_08_4.html", "struct_class_function_3_01_ret_type_07_type_1_1_5_08_07_args_8_8_8_08_4" ],
    [ "ClassFunctionData", "class_class_function_data.html", "class_class_function_data" ],
    [ "CollisionCheckHelper", "struct_collision_check_helper.html", null ],
    [ "CollisionCheckHelper< Type, MapType, false >", "struct_collision_check_helper_3_01_type_00_01_map_type_00_01false_01_4.html", null ],
    [ "CollisionCheckIsTileEmptyHelper", "struct_collision_check_is_tile_empty_helper.html", "struct_collision_check_is_tile_empty_helper" ],
    [ "DynamicArray", "class_dynamic_array.html", "class_dynamic_array" ],
    [ "EffectTestScene", "class_effect_test_scene.html", "class_effect_test_scene" ],
    [ "EmulateKeyData", "struct_emulate_key_data.html", "struct_emulate_key_data" ],
    [ "EnableGetter", "struct_enable_getter.html", null ],
    [ "EnableGetter< Type, false >", "struct_enable_getter_3_01_type_00_01false_01_4.html", null ],
    [ "EndingScene", "class_ending_scene.html", "class_ending_scene" ],
    [ "EventHandler", "class_event_handler.html", null ],
    [ "EventHandler< void(Signiture...)>", "class_event_handler_3_01void_07_signiture_8_8_8_08_4.html", "class_event_handler_3_01void_07_signiture_8_8_8_08_4" ],
    [ "Expresstion", "struct_expresstion.html", null ],
    [ "Expresstion< char >", "struct_expresstion_3_01char_01_4.html", null ],
    [ "Expresstion< wchar_t >", "struct_expresstion_3_01wchar__t_01_4.html", null ],
    [ "Function", "class_function.html", "class_function" ],
    [ "FunctionData", "class_function_data.html", "class_function_data" ],
    [ "FunctionDataBase", "class_function_data_base.html", "class_function_data_base" ],
    [ "GameOverScene", "class_game_over_scene.html", "class_game_over_scene" ],
    [ "GameResourseManager", "class_game_resourse_manager.html", "class_game_resourse_manager" ],
    [ "GetCollideRectangeCaller", "struct_get_collide_rectange_caller.html", null ],
    [ "GetCollideRectangeCaller< Type, false >", "struct_get_collide_rectange_caller_3_01_type_00_01false_01_4.html", null ],
    [ "GraphData", "struct_graph_data.html", "struct_graph_data" ],
    [ "ImageMaskRenderer", "class_image_mask_renderer.html", "class_image_mask_renderer" ],
    [ "ImageMosaicRenderer", "class_image_mosaic_renderer.html", "class_image_mosaic_renderer" ],
    [ "IMapTileLayor", "class_i_map_tile_layor.html", "class_i_map_tile_layor" ],
    [ "InputManager", "class_input_manager.html", "class_input_manager" ],
    [ "is_same_function_ptr_t", "structis__same__function__ptr__t.html", null ],
    [ "is_same_function_ptr_t< ret1(*)(Signiture...), ret1(*)(Signiture...)>", "structis__same__function__ptr__t_3_01ret1_07_5_08_07_signiture_8_8_8_08_00_01ret1_07_5_08_07_signiture_8_8_8_08_4.html", null ],
    [ "is_same_function_ptr_t< ret1(x1::*)(Signiture...), ret1(x1::*)(Signiture...)>", "structis__same__function__ptr__t_3_01ret1_07x1_1_1_5_08_07_signiture_8_8_8_08_00_01ret1_07x1_1_1_5_08_07_signiture_8_8_8_08_4.html", null ],
    [ "IsEmptyCaller", "struct_is_empty_caller.html", null ],
    [ "IsEmptyCaller< Type, false >", "struct_is_empty_caller_3_01_type_00_01false_01_4.html", null ],
    [ "LevelScene", "class_level_scene.html", "class_level_scene" ],
    [ "Map", "class_map.html", "class_map" ],
    [ "MapTile", "struct_map_tile.html", "struct_map_tile" ],
    [ "MapTileGetCollideRectangeCaller", "struct_map_tile_get_collide_rectange_caller.html", null ],
    [ "MapTileGetCollideRectangeCaller< Type, false, false, false >", "struct_map_tile_get_collide_rectange_caller_3_01_type_00_01false_00_01false_00_01false_01_4.html", null ],
    [ "MapTileGetCollideRectangeCaller< Type, false, false, true >", "struct_map_tile_get_collide_rectange_caller_3_01_type_00_01false_00_01false_00_01true_01_4.html", null ],
    [ "MapTileGetCollideRectangeCaller< Type, false, true, false >", "struct_map_tile_get_collide_rectange_caller_3_01_type_00_01false_00_01true_00_01false_01_4.html", null ],
    [ "MapTileGetCollideRectangeCaller< Type, false, true, true >", "struct_map_tile_get_collide_rectange_caller_3_01_type_00_01false_00_01true_00_01true_01_4.html", null ],
    [ "MapTileIsEmptyCaller", "struct_map_tile_is_empty_caller.html", null ],
    [ "MapTileIsEmptyCaller< Type, false >", "struct_map_tile_is_empty_caller_3_01_type_00_01false_01_4.html", null ],
    [ "MosaicRenderer", "class_mosaic_renderer.html", "class_mosaic_renderer" ],
    [ "OnCollideFromBottomCaller", "struct_on_collide_from_bottom_caller.html", null ],
    [ "OnCollideFromBottomCaller< Type, MapType, false >", "struct_on_collide_from_bottom_caller_3_01_type_00_01_map_type_00_01false_01_4.html", null ],
    [ "OnCollideFromSideCaller", "struct_on_collide_from_side_caller.html", null ],
    [ "OnCollideFromSideCaller< Type, MapType, false >", "struct_on_collide_from_side_caller_3_01_type_00_01_map_type_00_01false_01_4.html", null ],
    [ "OpeningScene", "class_opening_scene.html", "class_opening_scene" ],
    [ "Property", "class_property.html", null ],
    [ "Property< Ty, GetterRetType(GetterArgs...), SetterRetType(SetterArgs...)>", "class_property_3_01_ty_00_01_getter_ret_type_07_getter_args_8_8_8_08_00_01_setter_ret_type_07_setter_args_8_8_8_08_4.html", "class_property_3_01_ty_00_01_getter_ret_type_07_getter_args_8_8_8_08_00_01_setter_ret_type_07_setter_args_8_8_8_08_4" ],
    [ "ReflectionScene", "class_reflection_scene.html", "class_reflection_scene" ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "SceneManager", "class_scene_manager.html", "class_scene_manager" ],
    [ "ShutterRenderer", "class_shutter_renderer.html", "class_shutter_renderer" ],
    [ "ShutterScene", "class_shutter_scene.html", "class_shutter_scene" ],
    [ "StaticFunctionPointerAllocator", "struct_static_function_pointer_allocator.html", null ],
    [ "StaticFunctionPointerAllocator< Ret(Signiture...)>", "struct_static_function_pointer_allocator_3_01_ret_07_signiture_8_8_8_08_4.html", "struct_static_function_pointer_allocator_3_01_ret_07_signiture_8_8_8_08_4" ],
    [ "StencilBuffer", "class_stencil_buffer.html", "class_stencil_buffer" ],
    [ "TemporaryMap", "class_temporary_map.html", "class_temporary_map" ],
    [ "WaveEffect2Renderer", "class_wave_effect2_renderer.html", "class_wave_effect2_renderer" ],
    [ "WaveEffectRenderer", "class_wave_effect_renderer.html", "class_wave_effect_renderer" ],
    [ "WaveTestScene", "class_wave_test_scene.html", "class_wave_test_scene" ]
];